import type { Category, Settings } from './types.ts'
import { SETTINGS_ID } from './types.ts'

export const DEFAULT_SETTINGS: Settings = {
  id: SETTINGS_ID,
  displayName: 'Leonel',
  currency: 'USD',
  monthStartDay: 1,
  periodMode: 'pay',
  payday1: 1,
  payday2: 16,
  savePercent: 10,
  theme: 'system',
  onboarded: false,
}

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'home-credit', name: 'Home Credit', kind: 'expense', icon: 'creditCard', color: '#3E6B8A', monthlyLimitCents: 0, sortOrder: 0, archived: false },
  { id: 'pldt', name: 'PLDT', kind: 'expense', icon: 'wifi', color: '#4A6FA5', monthlyLimitCents: 0, sortOrder: 1, archived: false },
  { id: 'insurance', name: 'Insurance', kind: 'expense', icon: 'shield', color: '#2F6B4F', monthlyLimitCents: 0, sortOrder: 2, archived: false },
  { id: 'savings', name: 'Savings', kind: 'expense', icon: 'piggy', color: '#C9A227', monthlyLimitCents: 0, sortOrder: 3, archived: false },
  { id: 'lola', name: 'Lola', kind: 'expense', icon: 'heart', color: '#B4566C', monthlyLimitCents: 0, sortOrder: 4, archived: false },
  { id: 'atome', name: 'Atome', kind: 'expense', icon: 'device', color: '#6B5B95', monthlyLimitCents: 0, sortOrder: 5, archived: false },
  { id: 'electric', name: 'Electric', kind: 'expense', icon: 'zap', color: '#C9A227', monthlyLimitCents: 0, sortOrder: 6, archived: false },
  { id: 'food', name: 'Food', kind: 'expense', icon: 'utensils', color: '#C45C3E', monthlyLimitCents: 0, sortOrder: 7, archived: false },
  { id: 'gasoline', name: 'Gasoline', kind: 'expense', icon: 'gas', color: '#8A5A3E', monthlyLimitCents: 0, sortOrder: 8, archived: false },
  { id: 'others', name: 'Others', kind: 'expense', icon: 'more', color: '#6E726E', monthlyLimitCents: 0, sortOrder: 9, archived: false },
  { id: 'water', name: 'Water', kind: 'expense', icon: 'zap', color: '#3E6B8A', monthlyLimitCents: 0, sortOrder: 10, archived: false },
  { id: 'load', name: 'Load', kind: 'expense', icon: 'phone', color: '#6B5B95', monthlyLimitCents: 0, sortOrder: 11, archived: false },
  { id: 'trip', name: 'Trip', kind: 'expense', icon: 'plane', color: '#3E6B8A', monthlyLimitCents: 0, sortOrder: 12, archived: false },
  { id: 'school', name: 'School', kind: 'expense', icon: 'flag', color: '#4A6FA5', monthlyLimitCents: 0, sortOrder: 13, archived: false },
  { id: 'medicine', name: 'Medicine', kind: 'expense', icon: 'heart', color: '#B4566C', monthlyLimitCents: 0, sortOrder: 14, archived: false },
  { id: 'shopping', name: 'Shopping', kind: 'expense', icon: 'bag', color: '#C45C3E', monthlyLimitCents: 0, sortOrder: 15, archived: false },
  { id: 'car', name: 'Car', kind: 'expense', icon: 'car', color: '#8A5A3E', monthlyLimitCents: 0, sortOrder: 16, archived: false },
  { id: 'parking', name: 'Parking', kind: 'expense', icon: 'car', color: '#6E726E', monthlyLimitCents: 0, sortOrder: 16, archived: false },
  { id: 'laundry', name: 'Laundry', kind: 'expense', icon: 'repeat', color: '#4A6FA5', monthlyLimitCents: 0, sortOrder: 17, archived: false },
  { id: 'gifts', name: 'Gifts', kind: 'expense', icon: 'smile', color: '#B4566C', monthlyLimitCents: 0, sortOrder: 18, archived: false },
  { id: 'church', name: 'Church', kind: 'expense', icon: 'heart', color: '#2F6B4F', monthlyLimitCents: 0, sortOrder: 19, archived: false },
  { id: 'hoa', name: 'HOA', kind: 'expense', icon: 'home', color: '#3E6B8A', monthlyLimitCents: 0, sortOrder: 20, archived: false },
  { id: 'garbage', name: 'Garbage', kind: 'expense', icon: 'trash', color: '#6E726E', monthlyLimitCents: 0, sortOrder: 21, archived: false },
  { id: 'internet', name: 'Internet', kind: 'expense', icon: 'wifi', color: '#4A6FA5', monthlyLimitCents: 0, sortOrder: 22, archived: false },
  { id: 'subscriptions', name: 'Subscriptions', kind: 'expense', icon: 'repeat', color: '#6B5B95', monthlyLimitCents: 0, sortOrder: 23, archived: false },
  { id: 'haircut', name: 'Haircut', kind: 'expense', icon: 'smile', color: '#C9A227', monthlyLimitCents: 0, sortOrder: 24, archived: false },
  { id: 'parking-mall', name: 'Mall', kind: 'expense', icon: 'bag', color: '#C45C3E', monthlyLimitCents: 0, sortOrder: 25, archived: false },
  { id: 'toll', name: 'Toll', kind: 'expense', icon: 'car', color: '#8A5A3E', monthlyLimitCents: 0, sortOrder: 26, archived: false },
  { id: 'repair', name: 'Repair', kind: 'expense', icon: 'zap', color: '#C9A227', monthlyLimitCents: 0, sortOrder: 27, archived: false },
  { id: 'pets', name: 'Pets', kind: 'expense', icon: 'heart', color: '#B4566C', monthlyLimitCents: 0, sortOrder: 28, archived: false },
  { id: 'paycheck', name: 'Paycheck', kind: 'income', icon: 'bank', color: '#2F6B4F', monthlyLimitCents: 0, sortOrder: 100, archived: false },
  { id: 'other-income', name: 'Other income', kind: 'income', icon: 'plus', color: '#4E8B6A', monthlyLimitCents: 0, sortOrder: 101, archived: false },
  { id: 'side-income', name: 'Side income', kind: 'income', icon: 'wallet', color: '#3E6B8A', monthlyLimitCents: 0, sortOrder: 102, archived: false },
  { id: 'bonus', name: 'Bonus', kind: 'income', icon: 'piggy', color: '#C9A227', monthlyLimitCents: 0, sortOrder: 103, archived: false },
]

export const BILL_CATEGORY_IDS = [
  'home-credit',
  'pldt',
  'insurance',
  'savings',
  'lola',
  'atome',
  'electric',
] as const

export const EXTRA_CATEGORY_IDS = [
  'water',
  'load',
  'trip',
  'school',
  'medicine',
  'shopping',
  'car',
  'parking',
  'laundry',
  'gifts',
  'church',
  'hoa',
  'garbage',
  'internet',
  'subscriptions',
  'haircut',
  'parking-mall',
  'toll',
  'repair',
  'pets',
] as const

export const LEGACY_EXPENSE_IDS = [
  'housing',
  'groceries',
  'dining',
  'transport',
  'utilities',
  'health',
  'fun',
  'shopping',
  'subscriptions',
  'other-expense',
  'pocket',
] as const

export const ONBOARDING_BUDGET_IDS = ['home-credit', 'pldt', 'insurance', 'electric'] as const
